services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file: ".env"
    depends_on:
      - db

  db:
    image: postgres:17.0
    restart: always
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  postgres-data:
